Initial support for C++
trailofbits/vast pull request #316
Opened 2023-06-21 14:56 UTC by frabert

2023-06-28 08:40 UTC, frabert commented on include/vast/Translation/CodeGenContext.hpp
> +        std::string get_namespaced_for_decl_name(const clang::NamedDecl *decl) {
`VarDecl`s also need to have a scoped name in the case of static variables inside records (I think).
`VarDecl`s are not `TagDecl`s, but both are `NamedDecl`s so this allows using the same logic for both cases

2023-07-10 12:49 UTC, lkorenc commented
Also please move the newly added test to `HighLevel/CXX` (so it kind of mirrors the namespace `hl:cxx`).

2023-07-13 11:20 UTC, lkorenc requested changes

2023-07-13 11:20 UTC, lkorenc commented on include/vast/Dialect/HighLevel/HighLevelTypes.td
> +def RValue : HighLevelType< "RValue",
Copy & paste of `lvalue` extract that to shared helper.

2023-07-13 11:20 UTC, lkorenc commented on include/vast/Dialect/HighLevel/HighLevelTypes.td
> +def ReferenceType : HighLevelType< "Reference" > {
Can use the same helper as lvalue/rvalue. Also should implement `SubElementTypeInterface`.

2023-07-17 11:44 UTC, lkorenc approved these changes

2023-07-17 11:47 UTC, merged