Support for TypeOf types
trailofbits/vast pull request #323
Opened 2023-06-29 21:08 UTC by PappasBrent

Adds support for Clang's `TypeOfExprType` and `TypeOfType` to VAST.
- Adds the types `TypeOfExprType` and `TypeOfType`to `HighLevelTypes.td`. These types keep track of their desugared types (i.e., the type inside the call to `typeof()`), but do not yet track type qualifiers.
- Adds visit methods to the `CodeGenTypeVisitorMixin` for these new types.
- Add a single small test to VAST's test suite to verify that typeof types are lowered correctly.

2023-06-29 22:36 UTC, pgoodman requested changes

2023-06-29 22:36 UTC, pgoodman commented on include/vast/Dialect/HighLevel/HighLevelTypes.td
> +  let mnemonic = "typeofexpr";
`typeof.expr`?

2023-06-29 22:36 UTC, pgoodman commented on include/vast/Dialect/HighLevel/HighLevelTypes.td
> +  let mnemonic = "typeof";
`typeof.type`

2023-06-30 12:37 UTC, PappasBrent commented
I've committed and pushed changes to this branch addressing @pgoodman's comments, but for some reason they are not yet appearing in this PR

2023-08-17 13:21 UTC, Jezurko commented on include/vast/Translation/CodeGenTypeVisitor.hpp
> +        auto VisitTypeOfExprType(const clang::TypeOfExprType *ty, qualifiers quals = {}) -> mlir_type {
Because we also need single argument version for clang AST TypeVisitor.

2023-08-17 15:05 UTC, xlauko approved these changes

2023-08-17 15:05 UTC, merged