Add operations for C++ constructors and destructors
trailofbits/vast pull request #346
Opened 2023-07-21 08:55 UTC by frabert

2023-07-24 13:17 UTC, lkorenc requested changes

2023-07-24 13:17 UTC, lkorenc commented on include/vast/Translation/CodeGenContext.hpp
> +        struct is_funclike {
I am pretty sure there is some `mlir::` interface for this. Is there a reason it cannot be used?

Also we usually use `type_list` for these types of queries.

2023-07-25 09:09 UTC, frabert commented on include/vast/Translation/CodeGenDeclVisitor.hpp
> +        operation lookup_funclike< hl::FuncOp >(mangled_name_ref mangled) {
I think total specialization is allowed, but partial is not

2023-07-25 21:59 UTC, lkorenc commented on include/vast/Translation/CodeGenDeclVisitor.hpp
> +        operation lookup_funclike< hl::FuncOp >(mangled_name_ref mangled) {
Still I would probably use a concept and a type list (as they are re-usable & more in line how we deal with things).

2023-07-26 10:03 UTC, frabert commented on include/vast/Translation/CodeGenDeclVisitor.hpp
> +        operation lookup_funclike< hl::FuncOp >(mangled_name_ref mangled) {
I'm not sure I understood correctly what you meant by using a `concept` instead, but I've made the function do a static assertion + constexpr if on the template parameter type

2023-07-27 10:40 UTC, frabert commented
Having a separate region for the initializer lists is proving problematic, and I don't think I'd be able to bring it to this PR this week, so I think we should think about keeping it like this (no separate region) for now and think about how to handle it later.

2025-01-29 10:57 UTC, closed without merging